[workspace]
members = ["cargo:mmk-cli"]

[dist]
cargo-dist-version = "0.25.1"
ci = ["github"]
installers = ["shell", "powershell"]
targets = [
    "aarch64-apple-darwin",
    "x86_64-apple-darwin",
    "x86_64-unknown-linux-musl",
    "aarch64-unknown-linux-musl",
    "x86_64-pc-windows-msvc",
]
install-updater = false
pr-run-mode = "plan"
