[package]
name = "mmk-git"
description = "Git history walker for Mokumokuren."
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
mmk-core = { path = "../mmk-core" }
mmk-config = { path = "../mmk-config" }
ahash = { workspace = true }
anyhow = { workspace = true }
bincode = { workspace = true }
directories = { workspace = true }
globset = { workspace = true }
gix = { workspace = true }
rayon = { workspace = true }
serde = { workspace = true }
sha2 = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
